/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package app;

import javax.swing.JOptionPane;

/**
 *
 * @author Ygnacio
 */
public class Selector extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     * @param parent
     * @param modal
     */
    public Selector(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrdbtnArtista = new javax.swing.JRadioButton();
        jrdbtnPrecio = new javax.swing.JRadioButton();
        jrdbtnCantidad = new javax.swing.JRadioButton();
        jrdbtnDisquera = new javax.swing.JRadioButton();
        jrdbtnActivo = new javax.swing.JRadioButton();
        jrdbtnSencilloLider = new javax.swing.JRadioButton();
        jrdbtnID = new javax.swing.JRadioButton();
        jbtnCrearVista = new javax.swing.JButton();
        jrdbtnTipo = new javax.swing.JRadioButton();
        jbtnCancelar = new javax.swing.JButton();
        jrdbtnTamano = new javax.swing.JRadioButton();
        jrdbtnNombre = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Crear vista");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jrdbtnArtista.setText("Artista");

        jrdbtnPrecio.setText("Precio");

        jrdbtnCantidad.setText("Cantidad");

        jrdbtnDisquera.setText("Disquera");

        jrdbtnActivo.setText("Activo");

        jrdbtnSencilloLider.setText("Sencillo líder");

        jrdbtnID.setText("ID");

        jbtnCrearVista.setText("Crear vista");
        jbtnCrearVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCrearVistaActionPerformed(evt);
            }
        });

        jrdbtnTipo.setText("Tipo");

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jrdbtnTamano.setText("Tamaño");

        jrdbtnNombre.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Selector");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 0));
        jLabel9.setText("Vista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdbtnArtista)
                            .addComponent(jrdbtnNombre)
                            .addComponent(jrdbtnTamano)
                            .addComponent(jrdbtnTipo)
                            .addComponent(jrdbtnID))
                        .addGap(92, 240, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnCrearVista)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrdbtnSencilloLider)
                                    .addComponent(jrdbtnActivo)
                                    .addComponent(jrdbtnDisquera)
                                    .addComponent(jrdbtnCantidad)
                                    .addComponent(jrdbtnPrecio))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jbtnCancelar)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrdbtnPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrdbtnCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrdbtnDisquera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrdbtnActivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrdbtnSencilloLider))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrdbtnID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrdbtnTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrdbtnTamano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrdbtnNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrdbtnArtista)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCrearVista)
                    .addComponent(jbtnCancelar))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private static StringBuffer columnas = new StringBuffer("");
    private static int contador = 0;
    private static String ID;

    public static StringBuffer getConsulta() {
        return columnas;
    }

    public static int getContador() {
        return contador;
    }

    public static String getID() {
        return ID;
    }

    private void jbtnCrearVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCrearVistaActionPerformed
        Vinilos.banderita = 0;

        columnas = new StringBuffer("");
        contador = 0;
        ID = "";

        try {
            if (jrdbtnID.isSelected()) {
                columnas.append("idVinilo, ");
                contador++;
                ID += "0";
            }
            if (jrdbtnTipo.isSelected()) {
                columnas.append("tipo, ");
                contador++;
                ID += "1";
            }
            if (jrdbtnTamano.isSelected()) {
                columnas.append("tamano, ");
                contador++;
                ID += "2";
            }
            if (jrdbtnNombre.isSelected()) {
                columnas.append("nombre, ");
                contador++;
                ID += "3";
            }
            if (jrdbtnArtista.isSelected()) {
                columnas.append("artista, ");
                contador++;
                ID += "4";
            }
            if (jrdbtnPrecio.isSelected()) {
                columnas.append("precio, ");
                contador++;
                ID += "5";
            }
            if (jrdbtnCantidad.isSelected()) {
                columnas.append("cantidad, ");
                contador++;
                ID += "6";
            }
            if (jrdbtnDisquera.isSelected()) {
                columnas.append("disquera, ");
                contador++;
                ID += "7";
            }
            if (jrdbtnActivo.isSelected()) {
                columnas.append("activo, ");
                contador++;
                ID += "8";
            }
            if (jrdbtnSencilloLider.isSelected()) {
                columnas.append("sencilloLider, ");
                contador++;
                ID += "9";
            }

            columnas.deleteCharAt(columnas.length() - 1);
            columnas.deleteCharAt(columnas.length() - 1);

            this.setVisible(false);

        } catch (StringIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(this, "Seleccione al menos una "
                    + "columna antes de continuar.");
        }
    }//GEN-LAST:event_jbtnCrearVistaActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Selector dialog = new Selector(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnCrearVista;
    private javax.swing.JRadioButton jrdbtnActivo;
    private javax.swing.JRadioButton jrdbtnArtista;
    private javax.swing.JRadioButton jrdbtnCantidad;
    private javax.swing.JRadioButton jrdbtnDisquera;
    private javax.swing.JRadioButton jrdbtnID;
    private javax.swing.JRadioButton jrdbtnNombre;
    private javax.swing.JRadioButton jrdbtnPrecio;
    private javax.swing.JRadioButton jrdbtnSencilloLider;
    private javax.swing.JRadioButton jrdbtnTamano;
    private javax.swing.JRadioButton jrdbtnTipo;
    // End of variables declaration//GEN-END:variables
}
